/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NnStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLNnStockPriceElement extends Components.NnStockPrice, HTMLStencilElement {
    }
    var HTMLNnStockPriceElement: {
        prototype: HTMLNnStockPriceElement;
        new (): HTMLNnStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "nn-stock-price": HTMLNnStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface NnStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "nn-stock-price": NnStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nn-stock-price": LocalJSX.NnStockPrice & JSXBase.HTMLAttributes<HTMLNnStockPriceElement>;
        }
    }
}
