/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NnSpinner {
    }
    interface NnStockFinder {
    }
    interface NnStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLNnSpinnerElement extends Components.NnSpinner, HTMLStencilElement {
    }
    var HTMLNnSpinnerElement: {
        prototype: HTMLNnSpinnerElement;
        new (): HTMLNnSpinnerElement;
    };
    interface HTMLNnStockFinderElement extends Components.NnStockFinder, HTMLStencilElement {
    }
    var HTMLNnStockFinderElement: {
        prototype: HTMLNnStockFinderElement;
        new (): HTMLNnStockFinderElement;
    };
    interface HTMLNnStockPriceElement extends Components.NnStockPrice, HTMLStencilElement {
    }
    var HTMLNnStockPriceElement: {
        prototype: HTMLNnStockPriceElement;
        new (): HTMLNnStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "nn-spinner": HTMLNnSpinnerElement;
        "nn-stock-finder": HTMLNnStockFinderElement;
        "nn-stock-price": HTMLNnStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface NnSpinner {
    }
    interface NnStockFinder {
        "onNnSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface NnStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "nn-spinner": NnSpinner;
        "nn-stock-finder": NnStockFinder;
        "nn-stock-price": NnStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nn-spinner": LocalJSX.NnSpinner & JSXBase.HTMLAttributes<HTMLNnSpinnerElement>;
            "nn-stock-finder": LocalJSX.NnStockFinder & JSXBase.HTMLAttributes<HTMLNnStockFinderElement>;
            "nn-stock-price": LocalJSX.NnStockPrice & JSXBase.HTMLAttributes<HTMLNnStockPriceElement>;
        }
    }
}
